"""initial schema

Revision ID: 6c7cac7f3161
Revises: 
Create Date: 2026-08-16 15:46:29.776251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7cac7f3161'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_movie_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='fk_comentarios_usuario_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_tmdb_movie_id'), 'comentarios', ['tmdb_movie_id'], unique=False)
    op.create_index(op.f('ix_comentarios_usuario_id'), 'comentarios', ['usuario_id'], unique=False)
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_movie_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='fk_favoritos_usuario_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'tmdb_movie_id', name='uq_favorito_usuario_filme')
    )
    op.create_index(op.f('ix_favoritos_usuario_id'), 'favoritos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # MySQL não permite dropar um índice ainda usado por uma FK, então a
    # constraint precisa ser removida explicitamente antes do índice/tabela.
    op.drop_constraint('fk_favoritos_usuario_id', 'favoritos', type_='foreignkey')
    op.drop_index(op.f('ix_favoritos_usuario_id'), table_name='favoritos')
    op.drop_table('favoritos')
    op.drop_constraint('fk_comentarios_usuario_id', 'comentarios', type_='foreignkey')
    op.drop_index(op.f('ix_comentarios_usuario_id'), table_name='comentarios')
    op.drop_index(op.f('ix_comentarios_tmdb_movie_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
