"""add poster_path a comentarios

Revision ID: 9286b70fe465
Revises: ac04bc85ee9c
Create Date: 2026-08-16 17:37:47.226223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9286b70fe465'
down_revision: Union[str, None] = 'ac04bc85ee9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comentarios', sa.Column('poster_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comentarios', 'poster_path')
    # ### end Alembic commands ###
