"""add titulo a comentarios

Revision ID: ac04bc85ee9c
Revises: 6c7cac7f3161
Create Date: 2026-08-16 17:06:21.803543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac04bc85ee9c'
down_revision: Union[str, None] = '6c7cac7f3161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comentarios', sa.Column('titulo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comentarios', 'titulo')
    # ### end Alembic commands ###
